import Head from "next/head";

type Props = {
  value: string;
  keys?: number[];
};

export default function Test() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1>Component dummy</h1>
    </div>
  );
}
