import Head from "next/head";
import Image from "next/image";

import styles from "@styles/Home.module.scss";

export default function Home() {
  console.log(`render page Home`);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{" "}
          <span className={styles.logo}>
            <div className={styles.imageWrap}>
              <Image src='/vercel.svg' alt='Vercel Logo' fill />
            </div>
          </span>
        </a>
      </footer>
    </div>
  );
}
