import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { ReactElement } from "react";

import styles from "@styles/Home.module.scss";

type CardItem = { link: string; title: string; description?: string };

export default function Home(): ReactElement {
  console.log(`render page Home`);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>
        <p>
          Deployed: <time>2023/1/22</time>
        </p>

        <div className={styles.grid}>
          <Card
            link='https://nextjs.org/docs'
            title='Documentation'
            description='Find in-depth information about Next.js features and API.'
          />
          <Card
            link='https://nextjs.org/learn'
            title='Learn'
            description='Learn about Next.js in an interactive course with quizzes!'
          />
          <Card
            link='https://github.com/vercel/next.js/tree/canary/examples'
            title='Examples'
            description='Discover and deploy boilerplate example Next.js projects.'
          />
          <Card
            link='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            title='Deploy'
            description='Instantly deploy your Next.js site to a public URL with Vercel.'
          />

          <Card
            link='/monkey999.work/console'
            title='Console'
            description='Monkey999 console sample'
          />
          <Card
            link='/komorikosha'
            title='komorikosha'
            description='komorikosha sample'
          />
          <Card
            link='/component-test'
            title='component-test'
            description='component-test sample'
          />
          <Card
            link='/memo-test'
            title='React Memo test'
            description='React.memo, useCallback, useMemo sample'
          />

          <Card
            title='CSS Workout'
            link='/design-sample'
            description='CSSで適当に作ってるサンプルのデザイン'
          />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{" "}
          <span className={styles.logo}>
            <div className={styles.imageWrap}>
              <Image src='/vercel.svg' alt='Vercel Logo' fill />
            </div>
          </span>
        </a>
      </footer>
    </div>
  );
}

const Card: React.FC<CardItem> = ({
  link,
  title,
  description = "not has description",
}) => {
  return (
    <Link href={link} className={styles.card} shallow={false}>
      <h2>{title} &rarr;</h2>
      <p>{description}</p>
    </Link>
  );
};
