import styles from "@utils/styles/Test.module.scss";
import { Dummys } from "@utils/types/testType";
import Head from "next/head";
type Props = {
  value: string;
  keys?: number[];
};

export default function TestAtom() {
  const typetest: Dummys = {
    val: 123,
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <p className={styles.global_test_atom}>global test atom</p>
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1>Component dummy</h1>
    </div>
  );
}
